### PR TITLE
DEVOPS-112:  Providing a path to enable Hyper-V Isolation.  

### PR DESCRIPTION
**Pull request by zbeer**
This will enable the script to run on more servers.

### CODE REVIEW

**Comment by zbeer** [comment]
@jelster:  With this modification, I can build the specified containers on Windows Server 2019.  Let me know if you have any concerns or want to tweak the methodology!

**Comment by zbeer** [comment]
More details:  https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/hyperv-container

**Comment by zbeer** [comment]
I was unable to find a way to manage isolation mode in the DOCKERFILE itself.  The closest I got was this:
https://forums.docker.com/t/isolation-hyperv-tag-in-docker-compose-file/47573
... which basically says you can't do it in the docker-compose.yml.  

It's possible I'm missing something, though.

**Comment by jelster** [comment]
It looks like it's supported in v2 starting with v2.1 (https://docs.docker.com/compose/compose-file/compose-versioning/)[full version history]

> Version 2.1
An upgrade of version 2 that introduces new parameters only available with Docker Engine version 1.12.0+. Version 2.1 files are supported by Compose 1.9.0+.
Introduces the following additional parameters:
link_local_ips
isolation in build configurations and service definitions
labels for volumes and networks
name for volumes
userns_mode
healthcheck
sysctls
pids_limit
oom_kill_disable
cpu_period

It looks like `isolation` isn't introduced to v3 of compose until v3.5:

> Version 3.5
An upgrade of version 3 that introduces new parameters. It is only available with Docker Engine version 17.12.0 and higher.
Introduces the following additional parameters:
isolation in service definitions
name for networks, secrets and configs
shm_size in build configurations

It's odd because the version upgrade guide doesn't mention the lack of support for `isolation` in v3.x < 3.5, anyhow... 

So I think the question of whether or not this is needed hinges on whether docker engine 17.12.0+ is compatible with some of these host OS types, e.g., windows server ltsc2016 a.k.a. windows server 2016. A quick glance at the (https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility)[windows  containers compatibility matrix] says that ltsc host OS supports running ONLY images based on ltsc2016  - that covers many enterprise users who aren't updated past or to 1703. I think we'll want to definitely have the isolation flag set to hyper-v for that image, since that's the only way it will run on any newer host os. For building against 1803, eh maybe that one too. 1810+, I don't think we should include the flag (allow users to specify isolation at runtime) since there are more options for those users to decide on

**Comment by zbeer** [comment]
So where does that leave us?

**Comment by jelster** [comment]
fair point. To summarize:
* having flag in build script is good because we need to be able to choose whether the isolation is "baked" into the image on a granular basis (e.g., at build time)
* no windows 10 support for process isolation is bad
* I like jelly. :shipit:

**Comment by zbeer** [comment]
Hilariously, that's what I _thought_ it meant - I just wasn't confident enough in my understanding to put it out there.  Well, for the "choose whether isolation is baked into the image" bit.  

Thanks for bringing me along!

**Pull request merged**
